name: CI/CD Pipeline
#Trigger the workflow on push to main branch
on:
  push:
    branches: [ "main" ]

jobs:
  # step 1: Compile job
  compile:
    runs-on: self-hosted
    steps:
    # Checkout the repository
    - uses: actions/checkout@v4

    # set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # complile the code using Maven
    - name: compile
      run: mvn compile
  
  # step 2: Security Scan job
  security:
    name: Security Scan
    runs-on: self-hosted
    needs: compile
    steps:
    - uses: actions/checkout@v4

    # Install Trivy 
    - name: Install Trivy
      run: |
        sudo apt-get install -y wget gnupg
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update -y
        sudo apt-get install -y trivy
    # Run Trivy Scan on filesystem
    - name: Run Trivy Scan
      run: trivy fs --format table -o fs-report.txt .
    # Upload the Trivy report
    - name: Upload Scan report
      uses: actions/upload-artifact@v4
      with:
        name: security report
        path: fs-report.txt

  test:
    runs-on: self-hosted
    needs: security
    steps:
    # Checkout the repository
    - uses: actions/checkout@v4

    # set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # test the code using Maven
    - name: test
      run: mvn test

  build_package_sonarqube_scan:
    runs-on: self-hosted
    needs: test
    steps:
    # Checkout the repository
    - uses: actions/checkout@v4

    # set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # package the code using Maven
    - name: package
      run: mvn package
    
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-jar
        path: target/*.jar

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v7.0.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

  build_docker_image_and_push:
    runs-on: self-hosted
    needs: build_package_sonarqube_scan
    steps:
    # Checkout the repository
    - uses: actions/checkout@v4

    - name: Download JAR artifact
      uses: actions/download-artifact@v4
      with:
        name: app-jar
        path: app

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: anand1590/bankapp:latest
        file: ./Dockerfile

  deploy_docker_container:
    runs-on: self-hosted
    needs: build_docker_image_and_push
    steps:
    # Checkout the repository
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Deploy Docker Container
      run: docker pull anand1590/bankapp:latest
    - name: Deploy with Docker Compose
      run: |
        docker-compose down
        docker-compose up -d
